name: On Demand Build

on:
  workflow_dispatch:
    inputs:
      branch-name:  # id of input
        type: string
        description: 'Name of the repository branch. Ex: feature/SEPS-12345_Title-Of-Ticket'
        required: true
        default: main

concurrency:
    group: ${{ github.workflow }}-${{ inputs.branch-name }}
    cancel-in-progress: true
    
jobs:

  bicep-deploy:
    name: 'Bicep Deploy'
    runs-on: windows-latest
    steps:

      # Checkout the repository to the GitHub Actions runner
      - name: Checkout
        id: checkout
        uses: srinivas-kujala/workflows/.github/actions/checkout@main
        with:
          branch-name: ${{ github.ref_name }}

      # Authenticate to Az CLI using OIDC
      - name: 'Az CLI login'
        uses: srinivas-kujala/workflows/.github/actions/azure-login@main
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # Deploy
      - name: "Deployment"
        run: |
          .\infrastructure\create.ps1
        shell: powershell